import random

STORY_POINTS = [1, 2, 3, 5, 8, 13]

# Epic definitions per project
EPICS = {
    "MDA": [
        {"summary": "Student Dashboard Redesign", "status": "In Progress"},
        {"summary": "Course Catalogue & Search", "status": "In Progress"},
        {"summary": "Authentication & SSO Integration", "status": "Done"},
        {"summary": "Mobile Responsive Layout", "status": "In Progress"},
        {"summary": "Notification & Messaging System", "status": "In Progress"},
    ],
    "CRM": [
        {"summary": "Lead Management Pipeline", "status": "In Progress"},
        {"summary": "Application Form Workflow", "status": "In Progress"},
        {"summary": "Automated Email Campaigns", "status": "Done"},
        {"summary": "Reporting & Analytics Module", "status": "In Progress"},
        {"summary": "Integration with Payment Gateway", "status": "In Progress"},
    ],
    "INF": [
        {"summary": "Kubernetes Cluster Setup", "status": "Done"},
        {"summary": "CI/CD Pipeline Automation", "status": "In Progress"},
        {"summary": "Monitoring & Alerting Stack", "status": "In Progress"},
        {"summary": "Secrets Management Rollout", "status": "In Progress"},
        {"summary": "Database Backup & Recovery", "status": "In Progress"},
    ],
}

# Story templates per project
STORIES = {
    "MDA": [
        "Implement student profile page",
        "Add course enrollment flow",
        "Build grade overview widget",
        "Create schedule calendar component",
        "Design course detail page",
        "Implement search filters for courses",
        "Add dark mode toggle",
        "Build assignment submission form",
        "Integrate video player for lectures",
        "Add progress bar per course",
        "Implement email verification flow",
        "Build password reset page",
        "Add social login (Google/Microsoft)",
        "Create notifications bell component",
        "Implement in-app messaging",
        "Build student leaderboard",
        "Add file upload for assignments",
        "Create instructor profile view",
        "Implement course rating system",
        "Build attendance tracking dashboard",
        "Add language selector (i18n)",
        "Implement offline mode caching",
        "Create PDF certificate generation",
        "Build accessibility compliance audit",
        "Add student onboarding wizard",
        "Implement deep link routing",
        "Create course completion badge system",
        "Build keyboard navigation support",
        "Integrate analytics tracking",
        "Add GDPR consent modal",
    ],
    "CRM": [
        "Build lead capture form",
        "Implement lead scoring algorithm",
        "Create admissions kanban board",
        "Add automated follow-up emails",
        "Build document upload portal",
        "Implement interview scheduling",
        "Create enrollment confirmation flow",
        "Add CRM contact import (CSV)",
        "Build conversion funnel report",
        "Implement duplicate lead detection",
        "Create custom field editor",
        "Add bulk action on leads",
        "Build email template editor",
        "Implement A/B testing for emails",
        "Create reporting dashboard",
        "Add payment plan calculator",
        "Build refund request workflow",
        "Implement waitlist management",
        "Create agent performance dashboard",
        "Add SLA tracking for responses",
        "Build parent/guardian portal",
        "Implement multi-language support",
        "Create scholarship application flow",
        "Add compliance document checklist",
        "Build API webhook for CRM events",
        "Implement lead assignment rules",
        "Create term/cohort management",
        "Add signature capture for contracts",
        "Build alumni portal integration",
        "Implement GDPR data export",
    ],
    "INF": [
        "Set up Helm chart for API service",
        "Configure horizontal pod autoscaling",
        "Implement blue-green deployment",
        "Set up Prometheus metrics scraping",
        "Configure Grafana dashboard templates",
        "Implement log aggregation with Loki",
        "Set up HashiCorp Vault integration",
        "Configure RBAC policies for cluster",
        "Implement automated DB snapshots",
        "Set up staging environment parity",
        "Configure network policies",
        "Implement container image scanning",
        "Set up on-call rotation in PagerDuty",
        "Configure CDN for static assets",
        "Implement cost allocation tags",
        "Set up disaster recovery runbook",
        "Configure WAF rules",
        "Implement zero-downtime migrations",
        "Set up dependency vulnerability scanning",
        "Configure multi-region failover",
        "Implement GitOps workflow with ArgoCD",
        "Set up performance load testing",
        "Configure Redis caching layer",
        "Implement feature flag service",
        "Set up SOC2 audit logging",
        "Configure secrets rotation automation",
        "Implement API rate limiting",
        "Set up status page integration",
        "Configure backup retention policies",
        "Implement service mesh with Istio",
    ],
}

BUG_TEMPLATES = {
    "MDA": [
        ("Login page breaks on Safari iOS", "Critical"),
        ("Course videos not loading on slow connections", "High"),
        ("Grade calculation rounding error", "High"),
        ("Profile image upload fails >2MB", "Medium"),
        ("Calendar shows wrong timezone", "Medium"),
        ("Search returns duplicate results", "Medium"),
        ("Notification badge count incorrect", "Low"),
        ("PDF export missing last page", "High"),
        ("Dark mode flicker on page load", "Low"),
        ("Assignment due dates off by 1 day", "High"),
        ("Session expires too early", "Critical"),
        ("Email verification link expired too fast", "High"),
        ("Mobile menu not accessible via keyboard", "Medium"),
        ("Progress bar shows 101%", "Low"),
        ("Course rating saves twice on double click", "Medium"),
    ],
    "CRM": [
        ("Lead import fails with special characters", "Critical"),
        ("Duplicate leads created on form resubmit", "Critical"),
        ("Email campaign sends to unsubscribed users", "Critical"),
        ("Payment calculation wrong for installments", "High"),
        ("Document upload silently fails for PDF>10MB", "High"),
        ("Interview calendar double-booking allowed", "High"),
        ("Pipeline stage drag-drop broken on Firefox", "Medium"),
        ("Contact merge loses custom field data", "High"),
        ("Report date range off by timezone", "Medium"),
        ("Bulk email action ignores page 2+", "Medium"),
        ("Agent assignment resets on refresh", "Medium"),
        ("Webhook not firing on lead status change", "High"),
        ("CSV export truncates long notes", "Low"),
        ("SLA timer does not pause on weekends", "Medium"),
        ("Alumni portal login shows wrong name", "Low"),
    ],
    "INF": [
        ("Kubernetes pod OOM on peak traffic", "Critical"),
        ("CI pipeline fails intermittently on tests", "High"),
        ("Vault token renewal race condition", "Critical"),
        ("Backup job silently skips empty databases", "High"),
        ("Prometheus scrape timeout on heavy nodes", "High"),
        ("Grafana alert fires false positives", "Medium"),
        ("Log rotation not cleaning old files", "Medium"),
        ("ArgoCD sync stuck after merge conflict", "High"),
        ("Redis eviction causes cache stampede", "High"),
        ("Network policy blocks internal healthchecks", "Critical"),
        ("CDN cache not invalidated after deploy", "Medium"),
        ("Load balancer drops websocket connections", "High"),
        ("Secret rotation breaks app restart", "Critical"),
        ("Staging DB not in sync with prod schema", "Medium"),
        ("PagerDuty integration sends duplicate pages", "Low"),
    ],
}

TASK_TEMPLATES = {
    "MDA": [
        "Upgrade React to v18",
        "Migrate CSS modules to Tailwind",
        "Update API client to httpx",
        "Write component unit tests",
        "Configure ESLint rules",
        "Set up Storybook for components",
        "Optimize bundle size",
        "Write API integration tests",
        "Update Node.js to LTS",
        "Document component props",
    ],
    "CRM": [
        "Upgrade Django to 5.x",
        "Migrate to PostgreSQL 16",
        "Write Celery task unit tests",
        "Set up API documentation with Swagger",
        "Refactor authentication middleware",
        "Configure Redis for session caching",
        "Write E2E tests for lead pipeline",
        "Set up code coverage reporting",
        "Migrate legacy SQL queries to ORM",
        "Document CRM API endpoints",
    ],
    "INF": [
        "Audit all IAM permissions",
        "Update Terraform modules to latest",
        "Write runbook for incident response",
        "Review and prune old Docker images",
        "Update Kubernetes to 1.30",
        "Rotate all service account keys",
        "Document architecture diagrams",
        "Set up cost anomaly detection",
        "Review egress firewall rules",
        "Archive decommissioned services",
    ],
}

WORKFLOW_STATES = ["To Do", "In Progress", "In Review", "Blocked", "Done"]

# Active sprint state distribution
ACTIVE_SPRINT_WEIGHTS = {
    "To Do": 0.30,
    "In Progress": 0.35,
    "In Review": 0.15,
    "Blocked": 0.05,
    "Done": 0.15,
}


def pick_state_for_active_sprint() -> str:
    states = list(ACTIVE_SPRINT_WEIGHTS.keys())
    weights = list(ACTIVE_SPRINT_WEIGHTS.values())
    return random.choices(states, weights=weights, k=1)[0]


def pick_story_points() -> int:
    return random.choice(STORY_POINTS)
