USERS = [
    {
        "username": "alice.martin",
        "emailAddress": "alice.martin@marbella-academy.com",
        "displayName": "Alice Martin",
        "password": "Password123!",
        "role": "Developer",
        "team": "Frontend",
    },
    {
        "username": "bob.chen",
        "emailAddress": "bob.chen@marbella-academy.com",
        "displayName": "Bob Chen",
        "password": "Password123!",
        "role": "Developer",
        "team": "Backend",
    },
    {
        "username": "carol.lopez",
        "emailAddress": "carol.lopez@marbella-academy.com",
        "displayName": "Carol Lopez",
        "password": "Password123!",
        "role": "QA Engineer",
        "team": "QA",
    },
    {
        "username": "david.smith",
        "emailAddress": "david.smith@marbella-academy.com",
        "displayName": "David Smith",
        "password": "Password123!",
        "role": "Designer",
        "team": "Frontend",
    },
    {
        "username": "eva.johnson",
        "emailAddress": "eva.johnson@marbella-academy.com",
        "displayName": "Eva Johnson",
        "password": "Password123!",
        "role": "Scrum Master",
        "team": "Management",
    },
    {
        "username": "frank.mueller",
        "emailAddress": "frank.mueller@marbella-academy.com",
        "displayName": "Frank Mueller",
        "password": "Password123!",
        "role": "Product Owner",
        "team": "Management",
    },
    {
        "username": "grace.kim",
        "emailAddress": "grace.kim@marbella-academy.com",
        "displayName": "Grace Kim",
        "password": "Password123!",
        "role": "Developer",
        "team": "Backend",
    },
    {
        "username": "henry.patel",
        "emailAddress": "henry.patel@marbella-academy.com",
        "displayName": "Henry Patel",
        "password": "Password123!",
        "role": "DevOps Engineer",
        "team": "Infrastructure",
    },
]
